# -*- coding: utf-8 -*-
"""FinalProject_ANLT202.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1si4_nmZcRFkFoYcWAF94JmwXCy4lHE0b
"""

# Install libraries
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import os
import urllib.request

# Create a folder called 'data'
if not os.path.exists('data'):
    os.makedirs('data')

# The larger one (churn-bigml-80.csv, 2666 rows) for training and cross-validation,
# The smaller one (churn-bigml-20.csv, 667 rows) for final testing/evaluation.
# No need for additional splitting.

# Download the two dataset files automatically
files = {
    'https://raw.githubusercontent.com/SaskPolytechBIS/ML-DP-FinalProject/main/data/churn-bigml-80.csv': 'data/churn-bigml-80.csv',
    'https://raw.githubusercontent.com/SaskPolytechBIS/ML-DP-FinalProject/main/data/churn-bigml-20.csv': 'data/churn-bigml-20.csv'
}


for url, path in files.items():
    if not os.path.exists(path):
        print(f"Downloading {path} ...")
        urllib.request.urlretrieve(url, path)
        print("Done!")
    else:
        print(f"{path} already exists.")

df_train = pd.read_csv('data/churn-bigml-80.csv')
df_test  = pd.read_csv('data/churn-bigml-20.csv')

print(df_train.shape, df_test.shape)

# Data exploration & preprocessing
df_train.info()
df_test.info()

# Handling missing values
# Date cleaning: there are no missing values in both datasets
print(df_train.isnull().sum().sum(), df_test.isnull().sum().sum())

# Compute regression target: total_monthly_charge
df_train['total_monthly_charge'] = (df_train['Total day charge'] + df_train['Total eve charge'] +
                                    df_train['Total night charge'] + df_train['Total intl charge'])
df_test['total_monthly_charge'] = (df_test['Total day charge'] + df_test['Total eve charge'] +
                                   df_test['Total night charge'] + df_test['Total intl charge'])

# Map Churn to 0/1
df_train['Churn'] = df_train['Churn'].astype(int)
df_test['Churn'] = df_test['Churn'].astype(int)

# Features and targets
X_train = df_train.drop(['Churn', 'total_monthly_charge'], axis=1)
y_clf_train = df_train['Churn']
y_reg_train = df_train['total_monthly_charge']

X_test = df_test.drop(['Churn', 'total_monthly_charge'], axis=1)
y_clf_test = df_test['Churn']
y_reg_test = df_test['total_monthly_charge']

# Treat Area code as categorical
X_train['Area code'] = X_train['Area code'].astype(str)
X_test['Area code'] = X_test['Area code'].astype(str)

# Categorical and numerical columns
cat_cols = ['State', 'Area code', 'International plan', 'Voice mail plan']
num_cols = [col for col in X_train.columns if col not in cat_cols]

print("Categorical:", cat_cols)
print("Numerical:", num_cols)

# Outliers check (no handling needed, values reasonable)
print(X_train[num_cols].describe())



